/**
 * Parity harness (Build Prompt §10 items 3-4), run against a golden dataset
 * generated by driving the ACTUAL uploaded workbook via LibreOffice's UNO
 * bridge across the full cross-product specified in §10 item 2 (7,776
 * combinations — see parity/golden-dataset.csv and
 * parity/generate_golden_dataset.py for how it was produced, including the
 * LibreOffice-XLOOKUP compatibility note).
 *
 * Two separate assertions, per the spec's own split:
 *
 *  1. SCORE must match exactly, always, no exceptions (§10 item 3).
 *
 *  2. DECISION must match exactly, EXCEPT in the specific situations the
 *     spec documents as intentional deviations — and those cases must be
 *     asserted to differ in the specific expected direction (§10 item 4),
 *     not merely skipped. Three such situations arise from this dataset
 *     (deadline and resource flags are held neutral here, so short-deadline
 *     and resource-approval deviations don't appear in this particular
 *     dataset — those are covered by decision.test.ts instead):
 *
 *     a) §11 item 7 ("score of exactly 30 falls in an ambiguous branch"):
 *        the workbook's decline check is `D16 < 30` (strict), so a score of
 *        exactly 30 never declines in the workbook — it falls through to
 *        "Pending Approval". The spec is explicit ("Exactly 30 is a
 *        decline") and the new engine uses `<= 30`. Expected: workbook
 *        says Pending Approval, engine says declined.
 *
 *     b) §11 items 3/4 (the central structural change): the workbook's E9
 *        creative-approval flag forces "Pending Approval" ahead of the
 *        auto-approval check. The new engine's Stage A never looks at E9 at
 *        all (creative-resourcing is a Stage B concern that never changes
 *        the commercial decision). This only produces a visible decision
 *        difference when the workbook's E9 branch pre-empts what would
 *        otherwise have been "Auto-Approved" (score > 115) — when the
 *        workbook would have said "Pending Approval" anyway on score alone,
 *        both sides agree by coincidence, so no special-casing is needed
 *        there.
 *
 *     c) A boundary case NOT listed in §11 but observed directly in the
 *        workbook: `Calculator!G2`'s comment reads "Greater than this is
 *        auto-approved," but the live formula uses `D16 >= 115` (not
 *        strictly greater). The spec's own §3 table is explicit that
 *        auto-approval requires `score > auto threshold`. Per the build
 *        prompt's opening instruction ("the specification below supersedes
 *        the workbook wherever they disagree"), the engine follows the
 *        spec's literal ">" — but since this particular disagreement isn't
 *        in §11's list, it's also logged in docs/open-questions.md rather
 *        than silently absorbed. Expected: at score exactly 115 with no E9
 *        override, workbook auto-approves, engine says pending.
 *
 * Any row that doesn't fit one of the three patterns above and still
 * disagrees on decision is treated as a genuine parity bug and fails loudly.
 */

import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { computeStageA, type DecisionInputs } from "./decision.js";
import type { RuleSetPayload } from "./scoring.js";
import rulesetV1 from "../db/seed/ruleset-v1.generated.json" with { type: "json" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ruleSet = rulesetV1 as unknown as RuleSetPayload;

interface GoldenRow {
  tier: string;
  newRework: string;
  briefType: string;
  customerApproval: string;
  niche: boolean;
  strategic: boolean;
  creative: string;
  value: number;
  workbookScore: number;
  workbookApprovalText: string;
  workbookE9Note: string;
  workbookB14: string;
}

function parseGoldenCsv(csvPath: string): GoldenRow[] {
  const raw = readFileSync(csvPath, "utf-8").trim();
  const lines = raw.split(/\r?\n/);
  const [header, ...body] = lines;
  const cols = header!.split(",");
  return body.map((line) => {
    const cells = line.split(",");
    const rec: Record<string, string> = {};
    cols.forEach((c, i) => (rec[c] = cells[i] ?? ""));
    return {
      tier: rec.tier!,
      newRework: rec.new_rework!,
      briefType: rec.brief_type!,
      customerApproval: rec.customer_approval!,
      niche: rec.niche_ff_pre_approved === "True",
      strategic: rec.strategic_priority === "True",
      creative: rec.creative_approach!,
      value: Number(rec.value_potential_gbp),
      workbookScore: Number(rec.workbook_score),
      workbookApprovalText: rec.workbook_approval_text!,
      workbookE9Note: rec.workbook_e9_creative_note ?? "",
      workbookB14: rec.workbook_b14_auto_approval_dev!,
    };
  });
}

const EPSILON = 1e-6;

describe("parity: engine vs the actual workbook (§10)", () => {
  let rows: GoldenRow[] = [];

  beforeAll(() => {
    rows = parseGoldenCsv(path.join(__dirname, "../../parity/golden-dataset.csv"));
  });

  it("loaded the full 7,776-combination golden dataset", () => {
    expect(rows.length).toBe(7776);
  });

  it("matches the workbook's score exactly on every single combination", () => {
    for (const row of rows) {
      const inputs: DecisionInputs = {
        customerTier: row.tier,
        valuePotentialGbp: row.value,
        newRework: row.newRework,
        briefType: row.briefType,
        customerApproval: row.customerApproval,
        strategicPriority: row.strategic,
        creativeApproach: row.creative,
        nicheFfPreApproved: row.niche,
        marketingFlag: false,
        ppdFlag: false,
        gcmsFlag: false,
        daysUntilDeadline: 60, // matches the fixed/neutral deadline used to generate this dataset
      };
      const { score } = computeStageA(inputs, ruleSet);
      const diff = Math.abs(score - row.workbookScore);
      if (diff > EPSILON) {
        throw new Error(
          `Score mismatch for ${JSON.stringify(row)}: engine=${score} workbook=${row.workbookScore}`,
        );
      }
    }
  });

  it("matches or explains every decision, with expected deviations only in the three documented directions", () => {
    const counts = {
      exactMatch: 0,
      deviationExactly30: 0,
      deviationE9PreEmptsAutoApproval: 0,
      deviationBoundary115: 0,
      unexpectedMismatch: 0,
    };
    const unexpected: string[] = [];

    for (const row of rows) {
      const inputs: DecisionInputs = {
        customerTier: row.tier,
        valuePotentialGbp: row.value,
        newRework: row.newRework,
        briefType: row.briefType,
        customerApproval: row.customerApproval,
        strategicPriority: row.strategic,
        creativeApproach: row.creative,
        nicheFfPreApproved: row.niche,
        marketingFlag: false,
        ppdFlag: false,
        gcmsFlag: false,
        daysUntilDeadline: 60,
      };
      const { commercialDecision, score } = computeStageA(inputs, ruleSet);
      const engineText =
        commercialDecision === "auto_approved"
          ? "Auto-Approved"
          : commercialDecision === "declined"
            ? "Declined"
            : "Pending Approval";

      if (engineText === row.workbookApprovalText) {
        counts.exactMatch++;
        continue;
      }

      const e9NonBlank = row.workbookE9Note.trim().length > 0;
      const atExactly30 = Math.abs(score - 30) < EPSILON;
      const atExactly115 = Math.abs(score - 115) < EPSILON;

      if (
        atExactly30 &&
        row.workbookApprovalText === "Pending Approval" &&
        engineText === "Declined"
      ) {
        counts.deviationExactly30++;
        continue;
      }

      if (
        e9NonBlank &&
        score > 115 &&
        row.workbookApprovalText === "Pending Approval" &&
        engineText === "Auto-Approved"
      ) {
        counts.deviationE9PreEmptsAutoApproval++;
        continue;
      }

      if (
        atExactly115 &&
        !e9NonBlank &&
        row.workbookApprovalText === "Auto-Approved" &&
        engineText === "Pending Approval"
      ) {
        counts.deviationBoundary115++;
        continue;
      }

      counts.unexpectedMismatch++;
      unexpected.push(
        `${JSON.stringify(row)} => engine=${engineText}, score=${score}`,
      );
    }

    console.log("Parity decision classification:", counts);
    if (unexpected.length > 0) {
      console.log("First unexpected mismatches:", unexpected.slice(0, 10));
    }

    expect(counts.unexpectedMismatch).toBe(0);
    // Sanity: each documented deviation category should actually have been
    // exercised at least once by this dataset — if any of these are 0, the
    // test isn't actually proving what it claims to prove.
    //
    // Exception: deviationExactly30 is provably unreachable with the exact
    // value spread §10 item 2 mandates (0, 1, 1000, 30000, 35000, 100000,
    // 115000, 200000, 1000000) — checked exhaustively across every
    // qualitative combination, no total ever lands on exactly 30 with this
    // spread. That's a gap in the prescribed spread itself, not something
    // this harness can exercise. The exactly-30 behaviour is instead proven
    // directly by a hand-constructed fixture in decision.test.ts
    // ("a score of exactly the decline threshold (30) is declined, not
    // pending").
    expect(counts.deviationExactly30).toBe(0);
    expect(counts.deviationE9PreEmptsAutoApproval).toBeGreaterThan(0);
    expect(counts.deviationBoundary115).toBeGreaterThan(0);
    expect(counts.exactMatch).toBeGreaterThan(0);
  });
});
